# Generated by Django 3.1 on 2020-08-14 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=256)),
                ('cityCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cityUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryId', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=256)),
                ('countryCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('countryUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=256)),
                ('stateCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqContainer.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('ownerId', models.AutoField(primary_key=True, serialize=False)),
                ('ownerEmail', models.CharField(max_length=256)),
                ('ownerName', models.CharField(max_length=256)),
                ('ownerAddress', models.CharField(max_length=256)),
                ('ownerPhone', models.CharField(max_length=50)),
                ('ownerNeighborhood', models.CharField(max_length=50)),
                ('ownerPetName', models.CharField(max_length=50)),
                ('ownerPetType', models.CharField(max_length=50)),
                ('ownerCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ownerUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ownerCityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqContainer.cities')),
                ('ownerCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqContainer.countries')),
                ('ownerStateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqContainer.states')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='cityCountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqContainer.countries'),
        ),
        migrations.AddField(
            model_name='cities',
            name='cityStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqContainer.states'),
        ),
    ]
